openapi: 3.1.0
info:
  contact:
    email: support@apifellows.com
    name: '@apifellows Support Team'
    url: https://www.apifellows.com/support
  title: '@apifellows Online REST API Linter'
  version: 0.113.0
servers:
  - description: '@apifellows production environment'
    url: https://www.apifellows.com/wp-json/api-linter/v0
paths:
  /oas3/checkyaml:
    post:
      description: This endpoint validates an OpenAPI 3.1 specification provided directly as a YAML string in the body.
      operationId: validateSpecYaml
      requestBody:
        content:
          application/yaml:
            schema:
              description: The OpenAPI 3.1 specification as a YAML string.
              type: string
        required: true
      responses:
        '200':
          description: The OpenAPI specification was perfectly validated.
        '400':
          description: The OpenAPI specification is invalid yaml / client error.
        '422':
          description: The OpenAPI specification was validated, yaml is valid, but has some issues
        '500':
          description: server error
